### PR TITLE
Add clang-format

### LINKED ISSUE #60: Add clang-format config
# 🚀 Feature Request

Add a clang-format configuration file. This will be duplicated from `frc_control`. See uwreact/frc_control#33.

### PR DESCRIPTION
**Pull request by Matthew-Reynolds**
# Pull Request

Closes #60 

Duplicates changes from uwreact/frc_control#34 and uwreact/frc_control#35. This entails adding a clang-format config file, CI rules, and updating the README and PR template.

## Contribution Checklist

- [x] I have read the [contributing](https://github.com/uwreact/uwreact_robot/blob/master/CONTRIBUTING.md) guide.
- [x] I have referenced relevant issues.
- [x] I have labeled accordingly.
- [x] I have detailed my changes as much as possible.

## Change Checklist

- [x] I have added tests.
- [x] I have added necessary documentation.
- [ ] I have tested my changes on real hardware.

### CODE REVIEW

**Comment by Matthew-Reynolds** [comment]
Looks like the build is failing because our ROS version is still set to Kinetic in our CI config, which uses Ubuntu 16, which doesn't have `clang-format-7` available. This CI config issue is addressed in #58, which is ready for merging. In future, I shouldn't have made that change in that PR, it should have been separate. However, since #58 is about to land anyways, let's just leave this PR until then rather than going back and breaking it out.

**Comment by wmmc88** [comment]
Waiting on review from @micaelwm ?

**Comment by wmmc88** [comment]
Waiting on review from @michaelwm ?

**Comment by wmmc88** [comment]
@Matthew-Reynolds update and merge?

**Pull request merged**
